### ISSUE TITLE
同一の商品で、複数のURLを持つ場合の表現方法

### ISSUE THREAD

**Issue by 6h1sa** [hakka-ch/hakka.ch#14]
対応モデルによってそれぞれ別の販売ページを持つ商品の表現をどうにかしたい。
とりあえずデーターの表現はこんな感じ？

```toml
[[cloth]]
name = "hogehoge"
author = "foo"
  [[urls]]
    skinning = "avatar A"
    url = "https://example.com/A"
  [[urls]]
    skinning = "avatar B"
    url = "https://example.com/B"
```
